version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT


  online-book-store:
    depends_on:
      - mysqldb
    restart: on-failure
    image: book-store-app
    build: .
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DB
      SPRING_DATASOURCE_USERNAME: $MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
